import type { Metadata } from "next";
import evidence from "../../../public/research/giab-wes-nextflow/evidence/showcase.json";
import styles from "./showcase.module.css";

export const metadata: Metadata = {
  title: "GIAB HG001 caller comparison — evidence and execution status",
  description: "A reproducible GATK and DeepVariant comparison with verified synthetic integration and explicitly pending HG001 chr20–22 canonical results.",
  alternates: { canonical: "/research/giab-wes-nextflow" },
};
const repo = evidence.pipeline.repository;
const pinned = `${repo}/tree/${evidence.pipeline.sha}`;
const download = "/research/giab-wes-nextflow/evidence/";
const domains = evidence.domains.outputs;
const fmt = (n: number) => new Intl.NumberFormat("en-US").format(n);
const sections = [["scope", "Scope"], ["architecture", "Architecture"], ["methods", "Methods"], ["results", "Results"], ["reproducibility", "Evidence"], ["limitations", "Limitations"]];

export default function GiabShowcase() {
  return <main id="top" className={`interior-page ${styles.page}`}>
    <section className="page-hero shell">
      <div><p className="eyebrow"><span /> Reproducible genomics</p><h1>One sample.<br /><em>Two callers.</em><br />Traceable evidence.</h1></div>
      <div><p className="page-lede">A controlled GATK and DeepVariant comparison on GIAB HG001, with shared preprocessing, a fixed coding-domain definition and an explicit record of what has actually run.</p><p className={styles.status}>Synthetic M5 verified · Canonical results unavailable</p><a href={pinned} className="button primary">Inspect pipeline source <span aria-hidden="true">↗</span></a></div>
    </section>
    <nav className={`shell ${styles.contents}`} aria-label="Report contents">{sections.map(([id, title]) => <a key={id} href={`#${id}`}>{title}</a>)}</nav>
    <section id="scope" className={`shell page-section ${styles.section}`}>
      <p className="section-index">SCOPE / 01</p><div><h2>A defined comparison, with boundaries.</h2><p>The intended canonical input is the original paired Garvan HiSeq 2500 <code>NIST7035_TAAGGCGA_L001</code> lane from GIAB HG001. SRR3197785 identifies its lineage; it is not an SRA replacement for those source FASTQ bytes. The reference is GRCh38 no-alt <code>GCA_000001405.15</code>, with GIAB v4.2.1 truth reserved for downstream evaluation.</p><p>The first canonical target is chr20–22. No canonical run, caller ranking, accuracy estimate, QC measurement or resource comparison is reported here. Input-derived domain coordinates have been reproduced; that observation does not establish reference-base or runtime qualification.</p>
      <div className={styles.cards}><article><span>Planned canonical subset</span><strong>{fmt(domains.R_eval_holdout.bases)} bp</strong><p>{fmt(domains.R_eval_holdout.intervals)} fixed intervals · chr20–22</p></article><article><span>Approved full coding domain</span><strong>{fmt(domains.R_eval_full.bases)} bp</strong><p>{fmt(domains.R_eval_full.intervals)} fixed intervals · chr1–22</p></article></div>
      <p className={styles.source}>Coordinate evidence: <a href={`${download}domains.json`}>reproduced domain record</a>. These are evaluation denominators, not covered bases.</p></div>
    </section>
    <section id="architecture" className={styles.dark}><div className="shell page-section"><p className="eyebrow"><span /> Architecture</p><h2>Shared inputs. Independent calls. Common evaluation.</h2><ol className={styles.flow}><li><b>01 / Qualify</b><span>Source hashes, reference bases, indexes and runtime</span></li><li><b>02 / Preprocess once</b><span>Alignment, duplicate marking, BQSR and QC</span></li><li><b>03 / Call twice</b><span>GATK HaplotypeCaller · DeepVariant WES</span></li><li><b>04 / Evaluate</b><span>BCFtools normalization → RTG vcfeval → validated evidence</span></li></ol><p>Both callers must consume identical final BAM/BAI, reference and calling intervals. GATK uses recalibrated qualities; DeepVariant consumes original qualities through OQ. Benchmark truth is excluded from preprocessing and calling.</p></div></section>
    <section id="methods" className={`shell page-section ${styles.section}`}><p className="section-index">METHODS / 02</p><div><h2>A fixed denominator and an authoritative matcher.</h2><p>The target design is GENCODE v50 Basic, requiring protein-coding gene and transcript biotypes, with CDS plus stop-codon intervals. The full calling-domain constructor uses a merged 100 bp pad on chr1–22 and X; the planned canonical subset run selects chr20–22 from that padded domain. Evaluation intersects the unpadded design with GIAB high-confidence autosomal intervals; the chr20–22 subset is fixed before caller outcomes. Depth and query genotypes never redefine that denominator.</p><p>Symmetric normalization retains fully called, non-reference diploid genotypes, requires exact reference agreement and preserves raw caller FILTER provenance. BCFtools {evidence.synthetic.qualification.bcftools} prepares both sides for RTG Tools {evidence.synthetic.qualification.rtg} <code>vcfeval</code>. Query true positives and truth true positives remain distinct; undefined denominators remain missing.</p><p><a href={`${pinned}/docs/adr/0014-m5-common-normalization-and-benchmark.md`}>Preregistered M5 method</a> · <a href={`${pinned}/docs/canonical-results-contract.md`}>Canonical evidence contract</a> · <a href={`${pinned}/config/m2-resources.json`}>Input provenance</a></p></div></section>
    <section id="results" className={`shell page-section ${styles.section}`}><p className="section-index">RESULTS / 03</p><div><h2>Canonical comparison awaits execution.</h2><div className={styles.pending}><h3>Canonical results unavailable</h3><p>{evidence.canonical.reason}</p><p>SNP/indel accuracy, accuracy versus wall time/CPU/memory, coverage and canonical task measurements are unavailable. No zero values, synthetic substitutes or performance figures are presented as canonical observations.</p></div>
      <h3 className={styles.subheading}>Synthetic integration evidence</h3><p>The following values come from invented M5 representation fixtures processed by real tools. They test normalization and comparison behavior; they do not measure biological caller performance. The accepted M4 native caller interface separately qualified two SNP true positives without native-caller indel qualification.</p>
      <div className={styles.tableWrap} tabIndex={0} role="region" aria-label="Synthetic representation fixture metrics, horizontally scrollable"><table><caption>Invented fixtures only · retained M5 CI</caption><thead><tr><th scope="col">Fixture query</th><th scope="col">Class</th><th scope="col">TP query</th><th scope="col">TP truth</th><th scope="col">FP</th><th scope="col">FN</th><th scope="col">Precision</th><th scope="col">Recall</th><th scope="col">F1</th></tr></thead><tbody>{Object.entries(evidence.synthetic.metrics).flatMap(([caller, classes]) => Object.entries(classes).map(([type, m]) => <tr key={`${caller}-${type}`}><th scope="row">{caller}</th><td>{type}</td><td>{m.tp_query}</td><td>{m.tp_truth}</td><td>{m.fp}</td><td>{m.fn}</td><td>{m.precision === null ? "Unavailable" : m.precision.toFixed(3)}</td><td>{m.recall === null ? "Unavailable" : m.recall.toFixed(3)}</td><td>{m.f1 === null ? "Unavailable" : m.f1.toFixed(3)}</td></tr>))}</tbody></table></div><p>OTHER has no query or truth denominator; its precision, recall and F1 are undefined. Synthetic timings do not estimate WES cost.</p></div></section>
    <section id="reproducibility" className={`shell page-section ${styles.section}`}><p className="section-index">EVIDENCE / 04</p><div><h2>Inspect the execution record.</h2><p><a href={evidence.synthetic.run_url}>Retained M5 CI execution</a> establishes real normalization/benchmark execution, identical repeated normalization bytes, isolated staging and independent/both equivalence. {evidence.synthetic.artifact.verified_inventoried_files} retained file hashes were verified. The original failed attempt remains <a href={`${repo}/actions/runs/${evidence.synthetic.historical_failure.run_id}`}>available as history</a>.</p>
      <div className={styles.tableWrap} tabIndex={0} role="region" aria-label="Observed M5 execution modes"><table><caption>Actual Nextflow task states in the retained synthetic proof</caption><thead><tr><th scope="col">Mode</th><th scope="col">Completed</th><th scope="col">Cached</th></tr></thead><tbody>{Object.entries(evidence.synthetic.nextflow_modes).map(([mode, m]) => <tr key={mode}><th scope="row">{mode}</th><td>{m.statuses.COMPLETED}</td><td>{m.statuses.CACHED}</td></tr>)}</tbody></table></div>
      <div className={styles.tableWrap} tabIndex={0} role="region" aria-label="Environment qualification"><table><caption>Tested versus configured environments</caption><thead><tr><th scope="col">Environment</th><th scope="col">Evidence boundary</th></tr></thead><tbody><tr><th scope="row">Linux Docker + Nextflow</th><td>M5 synthetic execution verified in retained CI</td></tr><tr><th scope="row">Colab canonical runtime</th><td>Implemented qualification interface; canonical execution pending</td></tr><tr><th scope="row">Dash Explorer</th><td>Synthetic evidence, callbacks and exports tested locally; /giab-wes-nextflow/ route implemented; canonical bundle and public hosting pending</td></tr><tr><th scope="row">AWS HealthOmics</th><td>Operator inspection verified; exact Nextflow 26.04.0 parser, container cache and managed scientific qualification remain incomplete</td></tr><tr><th scope="row">SLURM, AWS Batch and Seqera Wave</th><td>Configured profiles only; no canonical execution qualification</td></tr><tr><th scope="row">Public website</th><td>This page is a source-bound consumer; it is not evidence of canonical execution</td></tr></tbody></table></div>
      <dl className={styles.provenance}><dt>Pipeline source binding</dt><dd><a href={pinned}><code>{evidence.pipeline.sha}</code></a></dd><dt>Version at bound source</dt><dd>{evidence.pipeline.version}</dd><dt>Synthetic tool package tested</dt><dd>{evidence.synthetic.installed_package.version} · <code>{evidence.synthetic.installed_package.repository_sha}</code></dd><dt>Website evidence manifest SHA-256</dt><dd><code>{evidence.evidence_manifest_sha256}</code></dd><dt>Retained CI archive SHA-256</dt><dd><code>{evidence.synthetic.artifact.sha256}</code></dd></dl>
      <div className={styles.links}><a href={`${download}manifest.json`}>Evidence manifest JSON ↓</a><a href={`${download}showcase.json`}>Website data JSON ↓</a><a href={`${download}m5.json`}>Verified M5 record ↓</a><a href={`${pinned}/explorer/README.md`}>Run Evidence Explorer locally ↗</a><a href="https://github.com/jcollins-bioinfo/giab-wes-nextflow/blob/f6613ad29fa51e12556083ff2a686bc5f01860dd/DEMO.md">Five-minute evidence walkthrough ↗</a><a href={`${pinned}/docs/canonical-analysis.md`}>Canonical execution guide ↗</a></div><p>Release candidate: unavailable. No published v1.0 release or public Explorer deployment is claimed. The planned apps.johnpatrickcollins.info/giab-wes-nextflow/ deployment uses one economical Lightsail container; image memory and managed HTTPS remain deployment gates. The existing Fargate/ALB configuration is disabled. The website importer currently admits only this reviewed synthetic snapshot; a returned canonical bundle requires validation by the pipeline result model and a separate reviewed website update.</p></div></section>
    <section id="limitations" className={`shell page-section ${styles.section}`}><p className="section-index">LIMITATIONS / 05</p><div><h2>What this evidence cannot establish.</h2><ul className={styles.limits}><li>One HG001 sample and one execution cannot establish population generalization or universal caller superiority.</li><li>DeepVariant WES training included HG001. Chr20–22 is a same-individual locus-held-out sensitivity; it does not establish independence from that individual’s training contribution.</li><li>Results on chr20–22 cannot be presented as completed full coding-exome or capture-kit performance. The fixed coding domain is not a capture-design reconstruction.</li><li>These research results do not establish clinical validity, production validation or historical professional Nextflow tenure.</li><li>Synthetic integration proves a bounded software contract. It does not supply biological accuracy, coverage, cost or uncertainty estimates.</li></ul><p>Future observed results must retain exact input and domain identities, preprocessing dependence, measured-versus-missing resources and the scope of applicable conclusions.</p></div></section>
  </main>;
}
